export type Tier = "Tier 1" | "Tier 2" | "Tier 3" | "Tier 4";
export type RouteType = "overwater" | "hybrid" | "overland";

export type RouteRecord = {
  rank: number;
  tier: Tier;
  tier_label: string;
  region: string;
  origin_iata: string;
  dest_iata: string;
  origin_city: string;
  dest_city: string;
  origin_country: string;
  dest_country: string;
  origin_country_code: string;
  dest_country_code: string;
  origin_lat: number;
  origin_lon: number;
  dest_lat: number;
  dest_lon: number;
  distance_nm: number;
  bearing_deg: number;
  range_limited: boolean;
  total_score: number;
  traffic_score: number;
  premium_demand_score: number;
  time_savings_score: number;
  viability_score: number;
  revenue_score: number;
  annual_pax: number;
  estimated_premium_pax: number;
  estimated_supersonic_revenue_M: number;
  business_fare_est: number;
  first_fare_est: number;
  bti_origin: number;
  bti_dest: number;
  overwater_pct: number;
  route_type: RouteType;
  supersonic_block_hr: number;
  subsonic_block_hr: number;
  time_saved_hr: number;
  time_saved_pct: number;
  effective_speed_kts: number;
  overwater_cruise_hr: number;
  boomless_cruise_hr: number;
  subsonic_phase_hr: number;
  overture_without_boomless_block_hr: number;
  boomless_savings_min: number;
  revenue_per_flight: number;
  cost_per_flight: number;
  profit_per_flight: number;
  annual_revenue_M: number;
  annual_cost_M: number;
  annual_profit_M: number;
  payback_years: number;
  breakeven_load_factor: number;
  flights_per_day: number;
  fuel_cost_per_flight: number;
  non_fuel_cost_per_flight: number;
  fuel_per_hr: number;
  total_fuel_kg: number;
  why_this_route: string;
};

export type SummaryStats = {
  total_routes_analyzed: number;
  routes_by_tier: Record<string, number>;
  routes_by_region: Record<string, number>;
  routes_by_route_type: Record<string, number>;
  total_addressable_premium_pax: number;
  total_addressable_revenue_B: number;
  avg_time_saved_hr: number;
  avg_overwater_pct: number;
  avg_score: number;
  overland_routes_unlocked: number;
  top_50_routes: Array<{
    rank: number;
    origin: string;
    dest: string;
    score: number;
    tier: string;
  }>;
};

export type Filters = {
  region: string;
  minScore: number;
  minDistance: number;
  maxDistance: number;
  tiers: Tier[];
  routeTypes: RouteType[];
};
